# Generated by Django 4.0.3 on 2022-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='stroy',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='story',
            field=models.TextField(blank=True),
        ),
    ]
