# Generated by Django 4.0.3 on 2022-03-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_videomodel_stroy_videomodel_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='birthday',
            field=models.CharField(max_length=4, verbose_name='روز تولد'),
        ),
    ]
