# Generated by Django 4.0.3 on 2022-03-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_aboutmodel_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail', to='api.imagemodel', verbose_name='بنر'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='published',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='story',
            field=models.TextField(blank=True, verbose_name='داستان'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to='videos', verbose_name='ویدیو'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_describe',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
